server:
  port: 8080
spring :
  application:
    name: npc-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npc_lessons?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
jwt:
  secret: daylatokenCuaCaoHaiLamDoAiBiet04