server:
  port: 8080
spring :
  application:
    name: npc-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npc_lessons?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Lam30112004
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: lamch301104@gmail.com
    password: igjc rmgo clmj xlkm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: daylatokenCuaCaoHaiLamDoAiBiet04